/**********************************************************************
 * GameGut - msw_input_keymap.cpp
 * Copyright (c) 1999-2005 Jason Perkins.
 * All rights reserved.
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the BSD-style license that is 
 * included with this library in the file LICENSE.txt.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 * files LICENSE.txt for more details. 
 **********************************************************************/

#include "core/core.h"

int utx_msw_keymap[] = 
{
	UT_KEY_UNKNOWN,         // 0x00
	UT_KEY_ESCAPE,          // 0x01
	UT_KEY_1,               // 0x02
	UT_KEY_2,               // 0x03
	UT_KEY_3,               // 0x04
	UT_KEY_4,               // 0x05
	UT_KEY_5,               // 0x06
	UT_KEY_6,               // 0x07
	UT_KEY_7,               // 0x08
	UT_KEY_8,               // 0x09
	UT_KEY_9,               // 0x0A
	UT_KEY_0,               // 0x0B
	UT_KEY_MINUS,           // 0x0C
	UT_KEY_EQUALS,          // 0x0D
	UT_KEY_BACKSPACE,       // 0x0E
	UT_KEY_TAB,             // 0x0F
	UT_KEY_Q,               // 0x10
	UT_KEY_W,               // 0x11
	UT_KEY_E,               // 0x12
	UT_KEY_R,               // 0x13
	UT_KEY_T,               // 0x14
	UT_KEY_Y,               // 0x15
	UT_KEY_U,               // 0x16
	UT_KEY_I,               // 0x17
	UT_KEY_O,               // 0x18
	UT_KEY_P,               // 0x19
	UT_KEY_LEFTBRACKET,     // 0x1A
	UT_KEY_RIGHTBRACKET,    // 0x1B
	UT_KEY_ENTER,           // 0x1C
	UT_KEY_LEFTCONTROL,     // 0x1D
	UT_KEY_A,               // 0x1E
	UT_KEY_S,               // 0x1F
	UT_KEY_D,               // 0x20
	UT_KEY_F,               // 0x21
	UT_KEY_G,               // 0x22
	UT_KEY_H,               // 0x23
	UT_KEY_J,               // 0x24
	UT_KEY_K,               // 0x25
	UT_KEY_L,               // 0x26
	UT_KEY_SEMICOLON,       // 0x27
	UT_KEY_APOSTROPHE,      // 0x28
	UT_KEY_GRAVE,           // 0x29
	UT_KEY_LEFTSHIFT,       // 0x2A
	UT_KEY_BACKSLASH,       // 0x2B
	UT_KEY_Z,               // 0x2C
	UT_KEY_X,               // 0x2D
	UT_KEY_C,               // 0x2E
	UT_KEY_V,               // 0x2F
	UT_KEY_B,               // 0x30
	UT_KEY_N,               // 0x31
	UT_KEY_M,               // 0x32
	UT_KEY_COMMA,           // 0x33
	UT_KEY_PERIOD,          // 0x34
	UT_KEY_SLASH,           // 0x35
	UT_KEY_RIGHTSHIFT,      // 0x36
	UT_KEY_NUMPADMULTIPLY,  // 0x37
	UT_KEY_LEFTALT,         // 0x38
	UT_KEY_SPACE,           // 0x39
	UT_KEY_CAPSLOCK,        // 0x3A
	UT_KEY_F1,              // 0x3B
	UT_KEY_F2,              // 0x3C
	UT_KEY_F3,              // 0x3D
	UT_KEY_F4,              // 0x3E
	UT_KEY_F5,              // 0x3F
	UT_KEY_F6,              // 0x40
	UT_KEY_F7,              // 0x41
	UT_KEY_F8,              // 0x42
	UT_KEY_F9,              // 0x43
	UT_KEY_F10,             // 0x44
	UT_KEY_NUMLOCK,         // 0x45
	UT_KEY_SCROLLLOCK,      // 0x46
	UT_KEY_NUMPAD7,         // 0x47
	UT_KEY_NUMPAD8,         // 0x48
	UT_KEY_NUMPAD9,         // 0x49
	UT_KEY_NUMPADMINUS,     // 0x4A
	UT_KEY_NUMPAD4,         // 0x4B
	UT_KEY_NUMPAD5,         // 0x4C
	UT_KEY_NUMPAD6,         // 0x4D
	UT_KEY_NUMPADPLUS,      // 0x4E
	UT_KEY_NUMPAD1,         // 0x4F
	UT_KEY_NUMPAD2,         // 0x50
	UT_KEY_NUMPAD3,         // 0x51
	UT_KEY_NUMPAD0,         // 0x52
	UT_KEY_NUMPADDECIMAL,   // 0x53
	UT_KEY_OEM102,          // 0x54
	UT_KEY_F11,             // 0x55
	UT_KEY_F12,             // 0x56
	UT_KEY_UNKNOWN,         // 0x57
	UT_KEY_UNKNOWN,         // 0x58
	UT_KEY_UNKNOWN,         // 0x59
	UT_KEY_UNKNOWN,         // 0x5A
	UT_KEY_UNKNOWN,         // 0x5B
	UT_KEY_UNKNOWN,         // 0x5C
	UT_KEY_UNKNOWN,         // 0x5D
	UT_KEY_UNKNOWN,         // 0x5E
	UT_KEY_UNKNOWN,         // 0x5F
	UT_KEY_UNKNOWN,         // 0x60
	UT_KEY_UNKNOWN,         // 0x61
	UT_KEY_UNKNOWN,         // 0x62
	UT_KEY_UNKNOWN,         // 0x63
	UT_KEY_F13,             // 0x64
	UT_KEY_F14,             // 0x65
	UT_KEY_F15,             // 0x66
	UT_KEY_UNKNOWN,         // 0x67
	UT_KEY_UNKNOWN,         // 0x68
	UT_KEY_UNKNOWN,         // 0x69
	UT_KEY_UNKNOWN,         // 0x6A
	UT_KEY_UNKNOWN,         // 0x6B
	UT_KEY_UNKNOWN,         // 0x6C
	UT_KEY_UNKNOWN,         // 0x6D
	UT_KEY_UNKNOWN,         // 0x6E
	UT_KEY_UNKNOWN,         // 0x6F
	UT_KEY_KANA,            // 0x70
	UT_KEY_UNKNOWN,         // 0x71
	UT_KEY_UNKNOWN,         // 0x72
	UT_KEY_ABNTC1,          // 0x73
	UT_KEY_UNKNOWN,         // 0x74
	UT_KEY_UNKNOWN,         // 0x75
	UT_KEY_UNKNOWN,         // 0x76
	UT_KEY_UNKNOWN,         // 0x77
	UT_KEY_UNKNOWN,         // 0x78
	UT_KEY_CONVERT,         // 0x79
	UT_KEY_UNKNOWN,         // 0x7A
	UT_KEY_NOCONVERT,       // 0x7B
	UT_KEY_UNKNOWN,         // 0x7C
	UT_KEY_YEN,             // 0x7D
	UT_KEY_ABNTC2,          // 0x7E
	UT_KEY_UNKNOWN,         // 0x7F
	UT_KEY_UNKNOWN,         // 0x80
	UT_KEY_UNKNOWN,         // 0x81
	UT_KEY_UNKNOWN,         // 0x82
	UT_KEY_UNKNOWN,         // 0x83
	UT_KEY_UNKNOWN,         // 0x84
	UT_KEY_UNKNOWN,         // 0x85
	UT_KEY_UNKNOWN,         // 0x86
	UT_KEY_UNKNOWN,         // 0x87
	UT_KEY_UNKNOWN,         // 0x88
	UT_KEY_UNKNOWN,         // 0x89
	UT_KEY_UNKNOWN,         // 0x8A
	UT_KEY_UNKNOWN,         // 0x8B
	UT_KEY_UNKNOWN,         // 0x8C
	UT_KEY_NUMPADEQUALS,    // 0x8D
	UT_KEY_UNKNOWN,         // 0x8E
	UT_KEY_UNKNOWN,         // 0x8F
	UT_KEY_PREVTRACK,       // 0x90
	UT_KEY_AT,              // 0x91
	UT_KEY_COLON,           // 0x92
	UT_KEY_UNDERLINE,       // 0x93
	UT_KEY_KANJI,           // 0x94
	UT_KEY_STOP,            // 0x95
	UT_KEY_AX,              // 0x96
	UT_KEY_UNLABELED,       // 0x97
	UT_KEY_UNKNOWN,         // 0x98
	UT_KEY_NEXTTRACK,       // 0x99
	UT_KEY_UNKNOWN,         // 0x9A
	UT_KEY_UNKNOWN,         // 0x9B
	UT_KEY_NUMPADENTER,     // 0x9C
	UT_KEY_RIGHTCONTROL,    // 0x9D
	UT_KEY_UNKNOWN,         // 0x9E
	UT_KEY_UNKNOWN,         // 0x9F
	UT_KEY_MUTE,            // 0xA0
	UT_KEY_CALCULATOR,      // 0xA1
	UT_KEY_PLAYPAUSE,       // 0xA2
	UT_KEY_UNKNOWN,         // 0xA3
	UT_KEY_MEDIASTOP,       // 0xA4
	UT_KEY_UNKNOWN,         // 0xA5
	UT_KEY_UNKNOWN,         // 0xA6
	UT_KEY_UNKNOWN,         // 0xA7
	UT_KEY_UNKNOWN,         // 0xA8
	UT_KEY_UNKNOWN,         // 0xA9
	UT_KEY_UNKNOWN,         // 0xAA
	UT_KEY_UNKNOWN,         // 0xAB
	UT_KEY_UNKNOWN,         // 0xAC
	UT_KEY_UNKNOWN,         // 0xAD
	UT_KEY_VOLUMEDOWN,      // 0xAE
	UT_KEY_UNKNOWN,         // 0xAF
	UT_KEY_VOLUMEUP,        // 0xB0
	UT_KEY_UNKNOWN,         // 0xB1
	UT_KEY_WEBHOME,         // 0xB2
	UT_KEY_NUMPADCOMMA,     // 0xB3
	UT_KEY_UNKNOWN,         // 0xB4
	UT_KEY_NUMPADDIVIDE,    // 0xB5
	UT_KEY_UNKNOWN,         // 0xB6
	UT_KEY_SYSRQ,           // 0xB7
	UT_KEY_RIGHTALT,        // 0xB8
	UT_KEY_UNKNOWN,         // 0xB9
	UT_KEY_UNKNOWN,         // 0xBA
	UT_KEY_UNKNOWN,         // 0xBB
	UT_KEY_UNKNOWN,         // 0xBC
	UT_KEY_UNKNOWN,         // 0xBD
	UT_KEY_UNKNOWN,         // 0xBE
	UT_KEY_UNKNOWN,         // 0xBF
	UT_KEY_UNKNOWN,         // 0xC0
	UT_KEY_UNKNOWN,         // 0xC1
	UT_KEY_UNKNOWN,         // 0xC2
	UT_KEY_UNKNOWN,         // 0xC3
	UT_KEY_UNKNOWN,         // 0xC4
	UT_KEY_PAUSE,           // 0xC5
	UT_KEY_UNKNOWN,         // 0xC6
	UT_KEY_HOME,            // 0xC7
	UT_KEY_UP,              // 0xC8
	UT_KEY_PAGEUP,          // 0xC9
	UT_KEY_UNKNOWN,         // 0xCA
	UT_KEY_LEFT,            // 0xCB
	UT_KEY_UNKNOWN,         // 0xCC
	UT_KEY_RIGHT,           // 0xCD
	UT_KEY_UNKNOWN,         // 0xCE
	UT_KEY_END,             // 0xCF
	UT_KEY_DOWN,            // 0xD0
	UT_KEY_PAGEDOWN,        // 0xD1
	UT_KEY_INSERT,          // 0xD2
	UT_KEY_DELETE,          // 0xD3
	UT_KEY_UNKNOWN,         // 0xD4
	UT_KEY_UNKNOWN,         // 0xD5
	UT_KEY_UNKNOWN,         // 0xD6
	UT_KEY_UNKNOWN,         // 0xD7
	UT_KEY_UNKNOWN,         // 0xD8
	UT_KEY_UNKNOWN,         // 0xD9
	UT_KEY_UNKNOWN,         // 0xDA
	UT_KEY_LEFTSYSTEM,      // 0xDB
	UT_KEY_RIGHTSYSTEM,     // 0xDC
	UT_KEY_MENU,            // 0xDD
	UT_KEY_POWER,           // 0xDE
	UT_KEY_SLEEP,           // 0xDF
	UT_KEY_UNKNOWN,         // 0xE0
	UT_KEY_UNKNOWN,         // 0xE1
	UT_KEY_UNKNOWN,         // 0xE2
	UT_KEY_WAKE,            // 0xE3
	UT_KEY_UNKNOWN,         // 0xE4
	UT_KEY_WEBSEARCH,       // 0xE5
	UT_KEY_WEBFAVORITES,    // 0xE6
	UT_KEY_WEBREFRESH,      // 0xE7
	UT_KEY_WEBSTOP,         // 0xE8
	UT_KEY_WEBFORWARD,      // 0xE9
	UT_KEY_WEBBACK,         // 0xEA
	UT_KEY_MYCOMPUTER,      // 0xEB
	UT_KEY_MAIL,            // 0xEC
	UT_KEY_MEDIASELECT,     // 0xED
};
