/**********************************************************************
 * GameGut - x11_input_keymap.cpp
 * Copyright (c) 1999-2005 Jason Perkins.
 * All rights reserved.
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the BSD-style license that is 
 * included with this library in the file LICENSE.txt.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 * files LICENSE.txt for more details. 
 **********************************************************************/

#include "core/core.h"

#define MAP(lo,hi)   (hi << 16) + lo

int utx_x11_keymap[] = 
{
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x00
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x01
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x02
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x03
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x04
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x05
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x06
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x07
	MAP(UT_KEY_UNKNOWN,      UT_KEY_BACKSPACE),        // 0x08
	MAP(UT_KEY_UNKNOWN,      UT_KEY_TAB),              // 0x09
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x0A
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x0B
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x0C
	MAP(UT_KEY_UNKNOWN,      UT_KEY_ENTER),            // 0x0D
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x0E
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x0F
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x10
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x11
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x12
	MAP(UT_KEY_UNKNOWN,      UT_KEY_PAUSE),            // 0x13
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x14
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x15
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x16
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x17
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x18
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x19
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x1A
	MAP(UT_KEY_UNKNOWN,      UT_KEY_ESCAPE),           // 0x1B
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x1C
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x1D
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x1E
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x1F
	MAP(UT_KEY_SPACE,        UT_KEY_UNKNOWN),          // 0x20
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x21
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x22
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x23
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x24
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x25
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x26
	MAP(UT_KEY_APOSTROPHE,   UT_KEY_UNKNOWN),          // 0x27
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x28
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x29
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x2A
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x2B
	MAP(UT_KEY_COMMA,        UT_KEY_UNKNOWN),          // 0x2C
	MAP(UT_KEY_MINUS,        UT_KEY_UNKNOWN),          // 0x2D
	MAP(UT_KEY_PERIOD,       UT_KEY_UNKNOWN),          // 0x2E
	MAP(UT_KEY_SLASH,        UT_KEY_UNKNOWN),          // 0x2F
	MAP(UT_KEY_0,            UT_KEY_UNKNOWN),          // 0x30
	MAP(UT_KEY_1,            UT_KEY_UNKNOWN),          // 0x31
	MAP(UT_KEY_2,            UT_KEY_UNKNOWN),          // 0x32
	MAP(UT_KEY_3,            UT_KEY_UNKNOWN),          // 0x33
	MAP(UT_KEY_4,            UT_KEY_UNKNOWN),          // 0x34
	MAP(UT_KEY_5,            UT_KEY_UNKNOWN),          // 0x35
	MAP(UT_KEY_6,            UT_KEY_UNKNOWN),          // 0x36
	MAP(UT_KEY_7,            UT_KEY_UNKNOWN),          // 0x37
	MAP(UT_KEY_8,            UT_KEY_UNKNOWN),          // 0x38
	MAP(UT_KEY_9,            UT_KEY_UNKNOWN),          // 0x39
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x3A
	MAP(UT_KEY_SEMICOLON,    UT_KEY_UNKNOWN),          // 0x3B
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x3C
	MAP(UT_KEY_EQUALS,       UT_KEY_UNKNOWN),          // 0x3D
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x3E
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x3F
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x40
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x41
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x42
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x43
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x44
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x45
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x46
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x47
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x48
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x49
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x4A
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x4B
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x4C
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x4D
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x4E
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x4F
	MAP(UT_KEY_UNKNOWN,      UT_KEY_HOME),             // 0x50
	MAP(UT_KEY_UNKNOWN,      UT_KEY_LEFT),             // 0x51
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UP),               // 0x52
	MAP(UT_KEY_UNKNOWN,      UT_KEY_RIGHT),            // 0x53
	MAP(UT_KEY_UNKNOWN,      UT_KEY_DOWN),             // 0x54
	MAP(UT_KEY_UNKNOWN,      UT_KEY_PAGEUP),           // 0x55
	MAP(UT_KEY_UNKNOWN,      UT_KEY_PAGEDOWN),         // 0x56
	MAP(UT_KEY_UNKNOWN,      UT_KEY_END),              // 0x57
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x58
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x59
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x5A
	MAP(UT_KEY_LEFTBRACKET,  UT_KEY_UNKNOWN),          // 0x5B
	MAP(UT_KEY_BACKSLASH,    UT_KEY_UNKNOWN),          // 0x5C
	MAP(UT_KEY_RIGHTBRACKET, UT_KEY_UNKNOWN),          // 0x5D
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x5E
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x5F
	MAP(UT_KEY_GRAVE,        UT_KEY_UNKNOWN),          // 0x60
	MAP(UT_KEY_A,            UT_KEY_UNKNOWN),          // 0x61
	MAP(UT_KEY_B,            UT_KEY_UNKNOWN),          // 0x62
	MAP(UT_KEY_C,            UT_KEY_INSERT),           // 0x63
	MAP(UT_KEY_D,            UT_KEY_UNKNOWN),          // 0x64
	MAP(UT_KEY_E,            UT_KEY_UNKNOWN),          // 0x65
	MAP(UT_KEY_F,            UT_KEY_UNKNOWN),          // 0x66
	MAP(UT_KEY_G,            UT_KEY_UNKNOWN),          // 0x67
	MAP(UT_KEY_H,            UT_KEY_UNKNOWN),          // 0x68
	MAP(UT_KEY_I,            UT_KEY_UNKNOWN),          // 0x69
	MAP(UT_KEY_J,            UT_KEY_UNKNOWN),          // 0x6A
	MAP(UT_KEY_K,            UT_KEY_UNKNOWN),          // 0x6B
	MAP(UT_KEY_L,            UT_KEY_UNKNOWN),          // 0x6C
	MAP(UT_KEY_M,            UT_KEY_UNKNOWN),          // 0x6D
	MAP(UT_KEY_N,            UT_KEY_UNKNOWN),          // 0x6E
	MAP(UT_KEY_O,            UT_KEY_MENU),             // 0x6F
	MAP(UT_KEY_P,            UT_KEY_UNKNOWN),          // 0x70
	MAP(UT_KEY_Q,            UT_KEY_UNKNOWN),          // 0x71
	MAP(UT_KEY_R,            UT_KEY_UNKNOWN),          // 0x72
	MAP(UT_KEY_S,            UT_KEY_UNKNOWN),          // 0x73
	MAP(UT_KEY_T,            UT_KEY_UNKNOWN),          // 0x74
	MAP(UT_KEY_U,            UT_KEY_UNKNOWN),          // 0x75
	MAP(UT_KEY_V,            UT_KEY_UNKNOWN),          // 0x76
	MAP(UT_KEY_W,            UT_KEY_UNKNOWN),          // 0x77
	MAP(UT_KEY_X,            UT_KEY_UNKNOWN),          // 0x78
	MAP(UT_KEY_Y,            UT_KEY_UNKNOWN),          // 0x79
	MAP(UT_KEY_Z,            UT_KEY_UNKNOWN),          // 0x7A
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x7B
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x7C
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x7D
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x7E
	MAP(UT_KEY_UNKNOWN,      UT_KEY_NUMLOCK),          // 0x7F
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x80
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x81
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x82
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x83
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x84
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x85
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x86
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x87
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x88
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x89
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x8A
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x8B
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x8C
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x8D
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x8E
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x8F
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x90
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x91
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x92
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x93
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0x94
	MAP(UT_KEY_UNKNOWN,      UT_KEY_NUMPAD7),          // 0x95
	MAP(UT_KEY_UNKNOWN,      UT_KEY_NUMPAD4),          // 0x96
	MAP(UT_KEY_UNKNOWN,      UT_KEY_NUMPAD8),          // 0x97
	MAP(UT_KEY_UNKNOWN,      UT_KEY_NUMPAD6),          // 0x98
	MAP(UT_KEY_UNKNOWN,      UT_KEY_NUMPAD2),          // 0x99
	MAP(UT_KEY_UNKNOWN,      UT_KEY_NUMPAD9),          // 0x9A
	MAP(UT_KEY_UNKNOWN,      UT_KEY_NUMPAD3),          // 0x9B
	MAP(UT_KEY_UNKNOWN,      UT_KEY_NUMPAD1),          // 0x9C
	MAP(UT_KEY_UNKNOWN,      UT_KEY_NUMPAD5),          // 0x9D
	MAP(UT_KEY_UNKNOWN,      UT_KEY_NUMPAD0),          // 0x9E
	MAP(UT_KEY_UNKNOWN,      UT_KEY_NUMPADDECIMAL),    // 0x9F
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xA0
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xA1
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xA2
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xA3
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xA4
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xA5
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xA6
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xA7
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xA8
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xA9
	MAP(UT_KEY_UNKNOWN,      UT_KEY_NUMPADMULTIPLY),   // 0xAA
	MAP(UT_KEY_UNKNOWN,      UT_KEY_NUMPADPLUS),       // 0xAB
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xAC
	MAP(UT_KEY_UNKNOWN,      UT_KEY_NUMPADMINUS),      // 0xAD
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xAE
	MAP(UT_KEY_UNKNOWN,      UT_KEY_NUMPADDIVIDE),     // 0xAF
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xB0
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xB1
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xB2
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xB3
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xB4
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xB5
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xB6
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xB7
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xB8
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xB9
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xBA
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xBB
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xBC
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xBD
	MAP(UT_KEY_UNKNOWN,      UT_KEY_F1),               // 0xBE
	MAP(UT_KEY_UNKNOWN,      UT_KEY_F2),               // 0xBF
	MAP(UT_KEY_UNKNOWN,      UT_KEY_F3),               // 0xC0
	MAP(UT_KEY_UNKNOWN,      UT_KEY_F4),               // 0xC1
	MAP(UT_KEY_UNKNOWN,      UT_KEY_F5),               // 0xC2
	MAP(UT_KEY_UNKNOWN,      UT_KEY_F6),               // 0xC3
	MAP(UT_KEY_UNKNOWN,      UT_KEY_F7),               // 0xC4
	MAP(UT_KEY_UNKNOWN,      UT_KEY_F8),               // 0xC5
	MAP(UT_KEY_UNKNOWN,      UT_KEY_F9),               // 0xC6
	MAP(UT_KEY_UNKNOWN,      UT_KEY_F10),              // 0xC7
	MAP(UT_KEY_UNKNOWN,      UT_KEY_F11),              // 0xC8
	MAP(UT_KEY_UNKNOWN,      UT_KEY_F12),              // 0xC9
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xCA
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xCB
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xCC
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xCD
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xCE
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xCF
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xD0
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xD1
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xD2
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xD3
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xD4
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xD5
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xD6
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xD7
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xD8
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xD9
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xDA
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xDB
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xDC
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xDD
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xDE
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xDF
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xE0
	MAP(UT_KEY_UNKNOWN,      UT_KEY_LEFTSHIFT),        // 0xE1
	MAP(UT_KEY_UNKNOWN,      UT_KEY_RIGHTSHIFT),       // 0xE2
	MAP(UT_KEY_UNKNOWN,      UT_KEY_LEFTCONTROL),      // 0xE3
	MAP(UT_KEY_UNKNOWN,      UT_KEY_RIGHTCONTROL),     // 0xE4
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xE5
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xE6
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xE7
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xE8
	MAP(UT_KEY_UNKNOWN,      UT_KEY_LEFTALT),          // 0xE9
	MAP(UT_KEY_UNKNOWN,      UT_KEY_RIGHTALT),         // 0xEA
	MAP(UT_KEY_UNKNOWN,      UT_KEY_LEFTSYSTEM),       // 0xEB
	MAP(UT_KEY_UNKNOWN,      UT_KEY_CAPSLOCK),         // 0xEC
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xED
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xEE
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xEF
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xF0
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xF1
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xF2
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xF3
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xF4
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xF5
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xF6
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xF7
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xF8
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xF9
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xFA
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xFB
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xFC
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xFD
	MAP(UT_KEY_UNKNOWN,      UT_KEY_UNKNOWN),          // 0xFE
	MAP(UT_KEY_UNKNOWN,      UT_KEY_DELETE)            // 0xFF
};
